apiVersion: apps/v1
kind: Deployment
metadata:
  name: flotta-apiserver
  namespace: flotta
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
      - name: apiserver
        image: quay.io/jdzon/flotta-api-server:classic
        imagePullPolicy: Always
        env:
          - name: DB_HOST
            value: "postgres-postgresql.default"
          - name: DB_PORT
            value: "5432"
          - name: DB_USERNAME
            value: "postgres"
          - name: DB_PASSWORD
            value: "qaU81M3ubo"
        args:
        - --etcd-servers=unix://kine.sock
        - --cert-dir=/tmp/certs
        - --secure-port=8443
        - --v=4
